### ISSUE TITLE
zhihu user的api不能使用

### ISSUE THREAD

**Issue by askintution** [bubao/zhihu-api#2]
Request
https://www.zhihu.com/api/v4/members/zhang-xiao-yu-45-67-74/articles?limit=10&offset=0&include=data%5B*%5D.comment_count%2Csuggest_edit%2Cis_normal%2Cthumbnail_extra_info%2Cthumbnail%2Ccan_comment%2Ccomment_permission%2Cadmin_closed_comment%2Ccontent%2Cvoteup_count%2Ccreated%2Cupdated%2Cupvoted_followees%2Cvoting%2Creview_info%2Cis_labeled%2Clabel_info%3Bdata%5B*%5D.author.badge%5B%3F%28type%3Dbest_answerer%29%5D.topics&sort_by=created

Response
{
    "error": {
        "code": 10002,
        "message": "10002:请求参数异常，请升级客户端后重试"
    }
}

**Comment by bubao** [comment]
在chrome浏览器中，`copy as  Nodejs fetch`，将请求参数添加进去

**Comment by askintution** [comment]
试了行，可行，不过知乎还用了参数加密。x-zse-86.

**Comment by bubao** [comment]
> 试了行，可行，不过知乎还用了参数加密。x-zse-86.

我也好久没维护这个项目了。最近断断续续维护，在 dev分支有提交

**Comment by askintution** [comment]
这个问题，有打算支持吗？

**Comment by bubao** [comment]
看情况

**Comment by askintution** [comment]
收集了些资料，你看有没有用

https://blog.csdn.net/zyc__python/article/details/105971031
https://blog.csdn.net/he_ranly/article/details/106861369

https://github.com/Pookii/BrandTools/blob/726a2fa49160655b524d44bc60b6727cddffcdd9/zhihu/zhihutopic.py

**Comment by bubao** [comment]
谢谢
